# Generated by Django 4.0.6 on 2022-08-02 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sujan_details',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('qualification', models.CharField(max_length=20)),
                ('ambitions', models.CharField(max_length=20)),
                ('hobbies', models.CharField(max_length=20)),
            ],
        ),
    ]
