# Generated by Django 4.0.6 on 2022-08-03 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sujan', '0003_alter_sujan_details_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sujan_details',
            name='city',
            field=models.CharField(max_length=20),
        ),
    ]
